// Generated by gencpp from file ros_pkg/multiplier.msg
// DO NOT EDIT!


#ifndef ROS_PKG_MESSAGE_MULTIPLIER_H
#define ROS_PKG_MESSAGE_MULTIPLIER_H

#include <ros/service_traits.h>


#include <ros_pkg/multiplierRequest.h>
#include <ros_pkg/multiplierResponse.h>


namespace ros_pkg
{

struct multiplier
{

typedef multiplierRequest Request;
typedef multiplierResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct multiplier
} // namespace ros_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_pkg::multiplier > {
  static const char* value()
  {
    return "a7d7d7065d45755acef7d4dcf908162a";
  }

  static const char* value(const ::ros_pkg::multiplier&) { return value(); }
};

template<>
struct DataType< ::ros_pkg::multiplier > {
  static const char* value()
  {
    return "ros_pkg/multiplier";
  }

  static const char* value(const ::ros_pkg::multiplier&) { return value(); }
};


// service_traits::MD5Sum< ::ros_pkg::multiplierRequest> should match
// service_traits::MD5Sum< ::ros_pkg::multiplier >
template<>
struct MD5Sum< ::ros_pkg::multiplierRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_pkg::multiplier >::value();
  }
  static const char* value(const ::ros_pkg::multiplierRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_pkg::multiplierRequest> should match
// service_traits::DataType< ::ros_pkg::multiplier >
template<>
struct DataType< ::ros_pkg::multiplierRequest>
{
  static const char* value()
  {
    return DataType< ::ros_pkg::multiplier >::value();
  }
  static const char* value(const ::ros_pkg::multiplierRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_pkg::multiplierResponse> should match
// service_traits::MD5Sum< ::ros_pkg::multiplier >
template<>
struct MD5Sum< ::ros_pkg::multiplierResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_pkg::multiplier >::value();
  }
  static const char* value(const ::ros_pkg::multiplierResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_pkg::multiplierResponse> should match
// service_traits::DataType< ::ros_pkg::multiplier >
template<>
struct DataType< ::ros_pkg::multiplierResponse>
{
  static const char* value()
  {
    return DataType< ::ros_pkg::multiplier >::value();
  }
  static const char* value(const ::ros_pkg::multiplierResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_PKG_MESSAGE_MULTIPLIER_H
